### ISSUE TITLE
[PE-D][Tester C] Exception for empty flag description not thrown properly

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2113-F10-1/tp#128] opened 2023-04-01 01:29 UTC
![Screenshot 2023-03-31 at 5.29.32 PM.png](https://raw.githubusercontent.com/T-Wan-Lin/ped/main/files/1eaccee3-a468-4c5d-824c-7f5c40a45696.png)

The exception does not specify for which flag is the argument is empty and is shown as `null`.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: T-Wan-Lin/ped#11

**Comment by ltzehan** [comment] 2023-04-01 14:17
Duplicate of #143

**Closed** 2023-04-01 14:23 UTC
